# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: user42 <user42@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/12/21 09:39:06 by user42            #+#    #+#              #
#    Updated: 2021/12/21 09:42:48 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


CC		=	gcc
CFLAGS =	-Wall -Wextra -Werror
SRC		=	
OBJ 	=	$(SRC:%.c=%.o)
NAME 	=	philo
LIBFT	=	libft.a

all : $(NAME)

$(NAME):	$(LIBFT) $(OBJ)
			@$(CC) $(CFLAGS) -o $(NAME) $(OBJ) ./srcs/libft/$(LIBFT)
			@echo "\n\033[32m[✓]\033[0m		[$(NAME) compiled]"

$(LIBFT):	
			@make --no-print-directory -C ./srcs/libft
			@cp ./srcs/libft/libft.a ./srcs/$(LIBFT)

clean:
			@rm -f *.o
			@rm -f ./srcs/*/*.o
			@make --no-print-directory -C ./srcs/libft clean

fclean:		clean
			@make --no-print-directory -C ./srcs/libft fclean
			@rm -f $(NAME) a.aout srcs/${LIBFT}
			
re:			fclean all
		
exec:		all
			@echo "\033[32m[✓]\033[0m		[$(NAME) executed]\n"
			@./$(NAME)
